app:
  audio_root: /Users/jeguan/audio-compare/audio_files/
  cache:
    max_size: 100
    ttl: 3600
  debug_mode: false
  log_level: INFO
  server:
    enable_cors: true
    enable_xsrf_protection: true
    host: localhost
    port: 8501
audio:
  dct_type: 2
  default_sample_rate: 22050
  fmax: null
  fmin: 0
  hop_length: 512
  n_fft: 2048
  n_mels: 128
  n_mfcc: 13
  norm: ortho
  spectral_rolloff_percentile: 0.85
  win_length: 2048
export:
  chart_format: png
  chart_scale: 2
  csv_encoding: utf-8
  csv_separator: ','
  report_template: html
feature:
  basic_features:
  - duration
  - rms
  - zero_crossing_rate
  mfcc_features:
  - mfcc_mean
  - mfcc_std
  - mfcc_delta
  - mfcc_delta2
  rhythm_features:
  - tempo
  - beat_frames
  - onset_strength
  spectral_features:
  - spectral_centroid
  - spectral_bandwidth
  - spectral_rolloff
  - spectral_contrast
  - spectral_flatness
file:
  max_batch_files: 50
  max_file_size: 100
  supported_formats:
  - wav
  - mp3
  - flac
  - ogg
  - m4a
  temp_dir: null
similarity:
  correlation_threshold: 0.8
  mse_threshold: 0.01
  snr_threshold: 20.0
ui:
  initial_sidebar_state: expanded
  layout: wide
  page_icon: 🎵
  page_title: TTS 音频验收工具
  theme:
    backgroundColor: '#ffffff'
    primaryColor: '#1f77b4'
    secondaryBackgroundColor: '#f0f2f6'
    textColor: '#262730'
visualization:
  axis_font_size: 12
  comparison_color1: '#1f77b4'
  comparison_color2: '#ff7f0e'
  comparison_height: 600
  mel_colorscale: Viridis
  mfcc_colorscale: RdBu
  spectrogram_height: 400
  title_font_size: 16
  waveform_color: '#1f77b4'
  waveform_height: 400
